name: athmovil_checkout_flutter
description: A new flutter plugin project.
version: 5.0.0
homepage: null

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  async: ^2.6.1
  uuid: ^4.0.0
  intl: ^0.19.0
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.3.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true # Add this line 

  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.evertec.athmovil.athmovil_checkout_flutter
        pluginClass: AthmovilCheckoutFlutterPlugin
      ios:
        pluginClass: AthmovilCheckoutFlutterPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/
flutter_intl:
  enabled: true
  class_name: AppLocalizations
